import Head from 'next/head'
import { Inter } from 'next/font/google'
import { ArrowLink } from "@/components/Icons"
import Layout from '@/components/Layout'
import Image from 'next/image'
import profilePic from "../../public/images/profile/ian_mult_hats.png"
import AnimatedText from '@/components/AnimatedText'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />

      </Head>
      <main className='flex items-center text-dark w-full min-h-screen
      dark:text-light'>
        <Layout className="pt-0">
          <div className="flex items-center justify-between w-full">
            <div className="w-1/2">
              <Image src={profilePic} alt="IanRiera" className='w-full
              h-auto max-w-sm rounded-lg shadow-none transition-shadow duration-300 ease-in-out hover:shadow-lg hover:shadow-black/30'
              priority
              sizes="(max-width: 768px) 100vw,
              (max-width: 1200px) 50vw,
              50vw" />
            </div>
            <div className="w-1/2 flex flex-col items-center self-center">
              <AnimatedText text="A Computer Vision Engineer With Multiple Hats."
                className='!text-6xl !text-left' />
              <p className='my-4 text-base font-medium'>
                As a skilled full-stack developer, I am dedicated to turning ideas into innovative web applications.
                Explore my latest projects and articles, showcasing my expertise in React.js and web development.
              </p>
              <div className='flex items-center self-start mt-2'>
                <Link href="/dummy.pdf" target={"_blank"}
                  className='flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold
                hover:bg-light hover:text-dark border border-solid border-transparent hover:border-dark
                dark:text-dark dark:bg-light hover:dark:bg-dark
                hover:dark:border-light hover:dark:text-light'
                  download={true}
                >Resume <ArrowLink className='ml-2' />
                </Link>
                <Link href="mailto:ian.riera.smolinska@gmail.com" target={"_blank"}
                className='ml-4 text-lg font-medium capitalize text-dark underline
                dark:text-light'
                >Contact</Link>
              </div>
            </div>
          </div>
        </Layout>
      </main>
    </>
  )
}
